### ISSUE TITLE
Can't use menu on mobile

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/forum-frontend#117]
On mobile, the menu button at the top right of the landing page seems to be non-functional. Therefore it's currently impossible to login (but this might also be blocked by #67). 

Tested on Chrome on iOS

**Comment by thewanderingeditor** [comment]
Actually, looks like I can't make this menu button work in any format (e.g., if I resize on desktop so the login button disappears)

**Comment by camilovegag** [comment]
Yes,  this is related to #97, will close this as its a dup :)
