### ISSUE TITLE
Add create option to academic credentials

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/forum-frontend#121]
# overview
you can not add a new type of credential on berlin, like in core

**Comment by camilovegag** [comment]
I can, maybe Ben faced a bug?

<img width="742" alt="Screenshot 2024-02-05 at 10 39 08 AM" src="https://github.com/lexicongovernance/forum-frontend/assets/59750365/8627f5eb-1e89-4364-8a75-bbb07472363f">

**Comment by MartinBenediktBusch** [comment]
@camilovegag @diegoalzate I tested it again and the feature is there so I will close this issue.
