### ISSUE TITLE
Not selecting an affiliation

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/forum-frontend#157]
# overview
When writing an affiliation if you just write one that is not in the possible options nothing gets stored in the database

**Comment by MartinBenediktBusch** [comment]
Issue will be fixed when validation gets triggered as you must select and affiliation. When you write an affiliation and not select one you should not be able to submit as validation will be triggered (as you must select and affiliation). If your affiliation is not present you must select the `Other` field.
